### ISSUE TITLE
ERROR: device "iPhone9,3" is not in bbgcid.json

### ISSUE THREAD

**Issue by Tezzlicious** [gotkrypto76/WebTSS#4]
[JSON] parsing elements
[Error] [TSSC] ERROR: device "iPhone9,3" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar (tihmstar@gmail.com) to get instructions how to contribute to this project.
[TSSR] WARNING: there was an error getting BasebandGoldCertID, continuing without requesting Baseband ticket

**Comment by Tezzlicious** [comment]
with an iPhone 7

**Comment by gotkrypto76** [comment]
This is alright. Blobs should still be saved. Tihmstar has already mentioned that it is safe to ignore these. However, if your blobs are not saving there's another issue you may be having. In that case I'll be sure to look into it for you!

**Comment by Tezzlicious** [comment]
Blobs are not generated for this device. Blobs for an iPad5,2 do. On the same server/db and cron.php job :)

**Comment by gotkrypto76** [comment]
Alright! Thanks for letting me know. I'll be sure to look into it today!

**Comment by 1Conan** [comment]
Just some more info 
Your baseband blobs won't be saved :D

**Comment by gotkrypto76** [comment]
Alright, I'll add that on to my todo list over Holliday break. Thanks for letting me know.

**Comment by Tezzlicious** [comment]
Seems to work with the latest version of tsschecker.
