### ISSUE TITLE
assign a user agent to api.ipsw.me call

### ISSUE THREAD

**Issue by cj123** [gotkrypto76/WebTSS#6]
in addDevice.php at ~ line 90, a request to api.ipsw.me is made, without a user agent specified.

as operator of api.ipsw.me, I ask in the [documentation](https://api.ipsw.me/docs/) that you assign a user agent to your application. Please consider doing so.

**Comment by gotkrypto76** [comment]
I'll do this right now! Sorry about that!

**Comment by gotkrypto76** [comment]
I've added a user agent to the calls made to api.ipsw.me. These changes can be found in addDevice.php and cron.php.
